version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: graphql-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/statesdb
    restart: always

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_GRAPHQL_ENDPOINT=http://localhost:8080/query
    depends_on:
      - backend
    restart: always
    
volumes:
  mongo_data:
