#!/usr/bin/env bash
set -e

# 1) Generate the frontend/.env file
cat > frontend/.env <<EOF
# Auto-generated by start.sh
VITE_GRAPHQL_ENDPOINT=http://localhost:8080/query
VITE_GOOGLE_MAPS_API_KEY='AIzaSyAU3HFklUOHU5qNbh5ILCKY2kmRXU8pz_g'
EOF
echo "→ Created frontend/.env with VITE_GRAPHQL_ENDPOINT"

# 2) (Optional) Pull any updated base images
docker-compose pull

# 3) Build & start all services in detached mode
docker-compose up -d --build

# 4) Show you what’s running
docker-compose ps
